name: Clang

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "17.0.0"
          arch: "arm64"

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          runVcpkgInstall: true
          vcpkgJsonGlob: vcpkg.json

      - uses: threeal/cmake-action@main
        with:
          generator: Ninja
          c-compiler: clang
          cxx-compiler: clang++
          options: CMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake