name: GCC

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on:
      ubuntu-latest
    steps:
      - uses: action/checkout@4.1.2

      - uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - uses: threeal/cmake-action@main
        with:
          generator: Ninja
          c-compiler: gcc
          cxx-compiler: g++