name: MSVC

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.2

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - uses: threeal/cmake-action@main
        with:
          generator: Ninja
          c-compiler: cl
          cxx-compiler: cl